### ISSUE TITLE
Unable to get View

### ISSUE THREAD

**Issue by tyrann0us** [brightnucleus/admin-page#1]
Hi,
I'm bootstrapping the package like this:
```
$adminPages = new AdminPages(
  new Config(
    'path/to/plugin/config/admin-pages.php'
  )
);
add_action(
  'init',
  [$adminPages, 'register']
);
```

`admin-pages.php` contains
```
return [
    '\BrightNucleus\AdminPage\AdminSubPage' => [
        'capability' => 'manage_options',
        'menu_title' => __('Title', 'text-domain'),
        'menu_slug' => 'vendor-title',
        'parent_slug' => 'options-general.php',
        'view' => 'path/to/plugin/views/options-page.php',
    ],
];
```

The option page gets added correctly but is empty. This seems to be the caused by
https://github.com/brightnucleus/admin-page/blob/d044cba20a0e246fdd9301edf095df9c6e0cba88/src/AdminPage.php#L181
setting `$view` to `false`.

Since this package is missing documentation I'm wondering whether my implementation is correct or am I missing something? I'm happy to provide more information.

Any feedback appreciated! Thanks!

**Comment by tyrann0us** [comment]
@schlessera, any change to take a look at this? I really want to use this package since it the "most OOP approach" of managing option pages I've seen so far.
Thanks!

**Comment by schlessera** [comment]
The problem seems to be locating the view.

> `'view' => 'path/to/plugin/views/options-page.php'`

The `'view'` config key should only be a view name (best without extension). The view is then found my adding a location to the `ViewBuilder` instance you pass along. See https://github.com/brightnucleus/view#instantiating-a-custom-viewbuilder

**Comment by tyrann0us** [comment]
Passing the `ViewBuilder` did the trick, thanks!
